// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	mysql "github.com/huahuoao/hertz_base/biz/dal/mysql/user"
	"github.com/huahuoao/hertz_base/biz/model/app/user"
	result "github.com/huahuoao/hertz_base/biz/model/common"
	"github.com/huahuoao/hertz_base/biz/model/do"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserRegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(user.UserRegisterResp)
	resp.Msg = "hello huahuo!"
	mysql.CreateUser(&do.User{
		Name: req.Username,
	})
	c.JSON(consts.StatusOK, result.New().Success(resp))
}
