// Code generated by hertz generator.

package user

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	result "github.com/huahuoao/hertz_base/biz/model/huahuo/common"
	user "github.com/huahuoao/hertz_base/biz/model/huahuo/user"
)

// Register .
// @router /user/register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserRegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}
	resp := new(user.UserRegisterResp)
	resp.Msg = "hello huahuo!"
	c.JSON(consts.StatusOK, result.New().SuccessWithMsg("注册成功", resp))
}
